# Generated by Django 6.0.7 on 2026-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0002_alter_payroll_owner_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='teacherpayrate',
            name='responsible_user',
        ),
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Calculated'), (2, 'Baned'), (3, 'No session'), (-1, 'Deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
