# Generated by Django 6.0.7 on 2026-08-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('manager', models.CharField(blank=True, max_length=150, null=True)),
                ('business_phone', models.CharField(max_length=14, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
