# Generated by Django 6.0.7 on 2026-08-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_school_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='owner_user',
        ),
        migrations.RemoveField(
            model_name='school',
            name='responsible_user',
        ),
    ]
