# Generated by Django 6.0.7 on 2026-08-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('education_officer', 'Education Officer'), ('finance_officer', 'Finance Officer')], max_length=20),
        ),
    ]
