# Generated by Django 6.0.7 on 2026-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('education_officer', 'Education_Officer'), ('finance_officer', 'Finance_Officer')], max_length=20),
        ),
    ]
