# Generated by Django 6.0.7 on 2026-08-05 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('reference_date', models.DateField()),
                ('reference_time', models.TimeField()),
                ('last_submit_date', models.DateField()),
                ('last_submit_time', models.TimeField()),
                ('report_description', models.TextField()),
                ('attendees', models.IntegerField()),
                ('absentees', models.IntegerField()),
                ('reviewer_description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Waiting_for_edit'), (2, 'Waiting_for_review'), (3, 'Approved'), (4, 'Rejected'), (-1, 'Deleted')], default=0)),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.coursesession')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ownered_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='responsibled_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
