# Generated by Django 6.0.7 on 2026-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_sessionreport_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
    ]
