# Generated by Django 6.0.7 on 2026-08-19 17:11

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_course_schedul_coursesession_course_schedule'),
        ('reports', '0003_sessionreport_is_delayed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionreport',
            name='last_submit_date',
        ),
        migrations.RemoveField(
            model_name='sessionreport',
            name='last_submit_time',
        ),
        migrations.RemoveField(
            model_name='sessionreport',
            name='reference_date',
        ),
        migrations.RemoveField(
            model_name='sessionreport',
            name='reference_time',
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='last_submit_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='reference_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='reviewer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Waiting_for_review'), (2, 'Approved'), (3, 'Rejected'), (-1, 'Deleted')], default=0),
        ),
        migrations.AddConstraint(
            model_name='sessionreport',
            constraint=models.UniqueConstraint(fields=('course_session',), name='unique_report_per_course_session'),
        ),
    ]
