# Generated by Django 6.0.7 on 2026-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_sessionreport_last_submit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='delay_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
