# Generated by Django 6.0.7 on 2026-08-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_academicterm_owner_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicterm',
            name='owner_user',
        ),
        migrations.RemoveField(
            model_name='academicterm',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='owner_user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='courseinstructor',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='owner_user',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='responsible_user',
        ),
        migrations.AddField(
            model_name='course',
            name='session_duration',
            field=models.IntegerField(choices=[(60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes')], default=90),
            preserve_default=False,
        ),
    ]
