# Generated by Django 6.0.7 on 2026-08-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_academicterm_owner_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')]),
        ),
    ]
