# Generated by Django 6.0.7 on 2026-08-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursesession_week_day_alter_courseschedule_week_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseschedule',
            old_name='course_instructore',
            new_name='course_instructor',
        ),
    ]
