# Generated by Django 6.0.7 on 2026-08-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_course_instructore_courseschedule_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='is_summer',
            field=models.BooleanField(default=False),
        ),
    ]
