# Generated by Django 6.0.7 on 2026-08-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_academicterm_is_summer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesession',
            old_name='course_schedul',
            new_name='course_schedule',
        ),
    ]
